In [10]:
import pandas as pd
import numpy as np

In [13]:
# 1.# Connect to a MySQL or PostgreSQL database using SQLAlchemy and pandas, then use pd.read_sql() 
# to load the entire 'restaurants' table (imagine Zomato backend) into a DataFrame and display the 
# first 5 rows.

from sqlalchemy import create_engine

df = pd.read_sql("select * from restaurants",create_engine("mysql+pymysql://root@localhost/tops_database"))
df

   rid              name       city  rating  delivery_charges
0    1   The Spice House  ahemdabad     4.5                30
1    2        Royal Dine  ahemdabad     3.4               100
2    3       Food Palace     Rajkot     3.0                20
3    4  great restaurant  ahemdabad     5.0                10

In [19]:
# 2.# Use pd.read_sql_query() to fetch only the 'name' and 'rating' columns from a 'movies' table 
# (think BookMyShow-like data) where rating is above 8, and print the resulting DataFrame.<br><br>
# <em><strong>Hint:</strong> Write a custom SQL SELECT query as the first argument to pd.read_sql_query().
# </em>

engine = "mysql+pymysql://root@localhost/tops_database"
query ="select name,rating from restaurants where rating>3"

df = pd.read_sql_query(query,engine)
df

               name  rating
0   The Spice House     4.5
1        Royal Dine     3.4
2  great restaurant     5.0

In [28]:
# 3.
# Read a JSON dataset from the URL https://jsonplaceholder.typicode.com/users using pandas, convert 
# it into a DataFrame, and print the usernames column.<br><br><em><strong>Hint:</strong> Use 
# pd.read_json() directly with the URL.</em>

json_data = pd.read_json('https://jsonplaceholder.typicode.com/users')
data_usernaem = pd.DataFrame(json_data['username'])
data_usernaem

           username
0              Bret
1         Antonette
2          Samantha
3          Karianne
4            Kamren
5  Leopoldo_Corkery
6      Elwyn.Skiles
7     Maxime_Nienow
8          Delphine
9    Moriah.Stanton

In [50]:
# 4.# You have two CSV files: 'orders.csv' (order_id, user_id, amount) and 'users.csv' (user_id, username)
# . Load both into DataFrames using pathlib for file paths, then merge them on 'user_id' to show a combined 
# table with username and amount.


orders = pd.read_csv("C:/Users/LENOVO/Downloads/orders.csv")
users = pd.read_csv("C:/Users/LENOVO/Downloads/users.csv")

print(orders.head(5))
print(users.head(5))

print("\n")


mergedata = pd.merge(orders,users)
print(mergedata.head())

   order_id  user_id   amount
0         1      101   250.00
1         2      102   899.50
2         3      101   120.00
3         4      103    45.75
4         5      104  1500.00
   user_id      username
0      101  rohit_sharma
1      102   priya_verma
2      103  suresh_kumar
3      104    neha_singh
4      105  anjali_mehta


   order_id  user_id   amount      username
0         1      101   250.00  rohit_sharma
1         2      102   899.50   priya_verma
2         3      101   120.00  rohit_sharma
3         4      103    45.75  suresh_kumar
4         5      104  1500.00    neha_singh

In [60]:

# 5. Concatenate two DataFrames representing 'today_orders' and 'yesterday_orders' (each with columns:
#  order_id, item, price), and display the combined DataFrame.<br><br><em><strong>Constraint:</strong>
#  Use pd.concat() and reset the index after concatenation.</em>

todays_df = pd.read_csv("C:/Users/LENOVO/Downloads/today_orders.csv")
yesterday_df = pd.read_csv("C:/Users/LENOVO/Downloads/yesterday_orders.csv")



concat_df = pd.concat([todays_df,yesterday_df],ignore_index=True)
concat_df

    order_id               item   price
0        201     Wireless Mouse   499.0
1        202  Bluetooth Speaker  1299.0
2        203       Notebook Set   150.0
3        204         Coffee Mug   199.0
4        205         Phone Case   249.0
5        206          Desk Lamp   650.0
6        207       Water Bottle   299.0
7        208          USB Cable   199.0
8        209           Backpack  1499.0
9        210         Wall Clock   599.0
10       195          Table Fan   899.0
11       196       Notebook Set   150.0
12       197          Earphones   399.0
13       198         Phone Case   249.0
14       199         Travel Mug   349.0
15       200       Bedsheet Set   799.0
16       203       Notebook Set   150.0
17       204         Coffee Mug   220.0
18       211           Keyboard   899.0
19       212           Yoga Mat   450.0