In [2]:
import pandas as pd

In [17]:
# 1.# Given a list of delivery timestamps as strings (e.g., ['2024-06-01 14:30', '2024-06-02 09:15', 
# '2024-06-03 20:45']), use pandas and pd.to_datetime() to convert them into datetime objects and 
# print the result.

date = ['2024-06-01 14:30', '2024-06-02 09:15',  '2024-06-03 20:45']

date_data = pd.DataFrame(date)
print(date_data[0].dtype)
date_data[0]= pd.to_datetime(date_data[0])
print(date_data[0].dtype)

str
datetime64[us]

In [31]:
# 2. Load a CSV file containing order dates from a Flipkart-style order history (column: 'order_date', 
# format: 'YYYY-MM-DD HH:MM:SS'). Extract the year, month, and weekday for each order and add them as 
# new columns in the DataFrame.

flipkart = pd.read_csv(r'D:\Tops Technowlogy\Data Scince\Dummy_Library_Assignment\csv_files\flipkart_order_history.csv')
flipkart['order_date'] =pd.to_datetime(flipkart['order_date'])
flipkart['year'] = flipkart['order_date'].dt.year
flipkart['month'] = flipkart['order_date'].dt.month
flipkart['day'] = flipkart['order_date'].dt.day
flipkart['week day']=flipkart['order_date'].dt.day_of_week

flipkart

,order_id,product_name,category,order_amount,payment_mode,order_date,year,month,day,week day
0,FLPKT8064,Realme Narzo 60,Electronics,51282,Debit Card,2023-01-07 00:50:51,2023,1,7,5
1,FLPKT8037,Lenovo IdeaPad Slim 3,Laptops,71695,Debit Card,2023-01-08 00:19:14,2023,1,8,6
2,FLPKT8039,Samsung Galaxy M14 5G,Audio,11462,Debit Card,2023-01-10 19:55:01,2023,1,10,1
3,FLPKT8067,HP Pavilion Laptop,Electronics,26293,UPI,2023-01-25 07:56:23,2023,1,25,2
4,FLPKT8034,OnePlus Nord CE 3 Lite,Wearables,13601,Credit Card,2023-02-02 12:53:00,2023,2,2,3
...,...,...,...,...,...,...,...,...,...,...
145,FLPKT8102,Apple iPhone 13,Electronics,12096,EMI,2024-12-01 07:44:30,2024,12,1,6
146,FLPKT8098,Sony WH-CH520 Headphones,Wearables,44132,UPI,2024-12-02 01:17:24,2024,12,2,0
147,FLPKT8115,OnePlus Nord CE 3 Lite,Wearables,82952,Cash on Delivery,2024-12-18 13:25:41,2024,12,18,2
148,FLPKT8010,OnePlus Nord CE 3 Lite,Wearables,5156,Debit Card,2024-12-28 11:33:13,2024,12,28,5
149,FLPKT8104,Realme Narzo 60,Electronics,52073,UPI,2024-12-29 08:03:50,2024,12,29,6

In [44]:
# 3. Set the 'order_date' column as the index of your DataFrame and use resampling to calculate the total 
# number of orders placed each week.<br><br><em><strong>Hint:</strong> Use df.resample('W').size() after 
# setting the datetime index.</em>


flipkart_timeseries = pd.read_csv(r'D:\Tops Technowlogy\Data Scince\Dummy_Library_Assignment\csv_files\flipkart_orders_timeseries.csv')

flipkart_timeseries['order_date']=pd.to_datetime(flipkart_timeseries['order_date'])
flipkart_timeseries.set_index("order_date",inplace=True)
week_order = flipkart_timeseries.resample("W").size()
week_order

order_date
2024-01-07     5
2024-01-14     6
2024-01-21     0
2024-01-28     8
2024-02-04     4
2024-02-11     3
2024-02-18     9
2024-02-25     5
2024-03-03     5
2024-03-10     5
2024-03-17    10
2024-03-24     6
2024-03-31     1
2024-04-07     5
2024-04-14     8
2024-04-21     7
2024-04-28     5
2024-05-05     3
2024-05-12    12
2024-05-19     2
2024-05-26     2
2024-06-02     8
2024-06-09     1
2024-06-16     5
2024-06-23     3
2024-06-30     3
2024-07-07    10
2024-07-14    11
2024-07-21     9
2024-07-28     9
2024-08-04     8
2024-08-11     4
2024-08-18    10
2024-08-25     5
2024-09-01     4
2024-09-08     4
2024-09-15     5
2024-09-22     6
2024-09-29     4
2024-10-06     6
2024-10-13     6
2024-10-20    12
2024-10-27    11
2024-11-03     4
2024-11-10     5
2024-11-17     4
2024-11-24     8
2024-12-01     4
2024-12-08     5
2024-12-15     5
2024-12-22     3
2024-12-29     6
2025-01-05     1
Freq: W-SUN, dtype: int64

In [ ]:
# 4. Suppose you have a DataFrame of Instagram posts with a 'posted_at' column in UTC.
#  Convert these timestamps to 'Asia/Kolkata' timezone and display the first 5 converted times.

timezone = pd.read_csv(r'D:\Tops Technowlogy\Data Scince\Dummy_Library_Assignment\csv_files\instagram_posts.csv')
timezone['posted_at'] = pd.to_datetime(timezone['posted_at'])
timezone['indian_time'] = timezone['posted_at'].dt.tz_convert("Asia/Kolkata")
timezone

,post_id,username,post_type,caption,likes,comments,posted_at,indian_time
0,IGP6010,artsy_soul,Photo,Sunset vibes 🌅,41389,503,2024-07-01 01:35:40+00:00,2024-07-01 07:05:40+05:30
1,IGP6027,artsy_soul,Story,Behind the scenes 🎬,48997,1121,2024-07-01 02:34:53+00:00,2024-07-01 08:04:53+05:30
2,IGP6064,gadgetguru,Story,Book of the month 📖,23822,1414,2024-07-01 03:38:51+00:00,2024-07-01 09:08:51+05:30
3,IGP6076,bookwormz,Photo,Tech unboxing time 📦,48303,1953,2024-07-01 10:15:45+00:00,2024-07-01 15:45:45+05:30
4,IGP6041,artsy_soul,Photo,My furry friend 🐶,8904,101,2024-07-01 17:08:19+00:00,2024-07-01 22:38:19+05:30
...,...,...,...,...,...,...,...,...
75,IGP6029,petloverz,Story,My furry friend 🐶,12315,387,2024-07-10 06:53:36+00:00,2024-07-10 12:23:36+05:30
76,IGP6065,foodie_hub,Story,New arrivals in store!,578,716,2024-07-10 08:56:02+00:00,2024-07-10 14:26:02+05:30
77,IGP6079,travel_diaries,Reel,Book of the month 📖,36393,439,2024-07-10 19:14:57+00:00,2024-07-11 00:44:57+05:30
78,IGP6049,travel_diaries,Carousel,Behind the scenes 🎬,16009,1937,2024-07-10 20:03:58+00:00,2024-07-11 01:33:58+05:30
79,IGP6052,travel_diaries,Story,Book of the month 📖,33939,1544,2024-07-10 21:18:43+00:00,2024-07-11 02:48:43+05:30

In [71]:
# 5.# Create a new feature called 'is_weekend' in your DataFrame that marks True if an order was 
# placed on Saturday or Sunday, and False otherwise.<br><br><em><strong>Constraint:</strong> Do 
# not use any external libraries except pandas and numpy.</em>


weekend = pd.read_csv("D:\Tops Technowlogy\Data Scince\Dummy_Library_Assignment\csv_files\orders_weekend_feature.csv")

weekend['order_date'] = pd.to_datetime(weekend['order_date'])
weekend['is_weekend ']= weekend['order_date'].dt.day_of_week >= 5
weekend.head()

<>:6: SyntaxWarning: "\T" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\T"? A raw string is also an option.
<>:6: SyntaxWarning: "\T" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\T"? A raw string is also an option.
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19848\2408886429.py:6: SyntaxWarning: "\T" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\T"? A raw string is also an option.
  weekend = pd.read_csv("D:\Tops Technowlogy\Data Scince\Dummy_Library_Assignment\csv_files\orders_weekend_feature.csv")

,order_id,product_name,order_amount,payment_mode,order_date,is_weekend
0,ORD9554,Apple iPhone 13,7058,UPI,2024-01-01 15:16:34,False
1,ORD9676,Apple iPhone 13,37368,Credit Card,2024-01-03 08:48:53,False
2,ORD9588,HP Pavilion Laptop,15157,Debit Card,2024-01-04 15:31:27,False
3,ORD9616,OnePlus Nord CE 3 Lite,17200,EMI,2024-01-06 09:30:35,True
4,ORD9514,Samsung Galaxy M14 5G,3500,Debit Card,2024-01-06 10:49:07,True